# Generated by Django 5.0.4 on 2024-05-02 03:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_guests', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('date_of_booking', models.DateField(default=django.utils.timezone.now)),
                ('time_of_booking', models.IntegerField(choices=[(0, datetime.time(12, 30)), (1, datetime.time(13, 0)), (2, datetime.time(13, 30)), (3, datetime.time(14, 0)), (4, datetime.time(14, 30)), (5, datetime.time(15, 0)), (6, datetime.time(15, 30)), (7, datetime.time(16, 0)), (8, datetime.time(16, 30))], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
